# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f77084cad57bbef80160555cbb6bb460ea885a86645ca6152612f532251880a185ac2186bb38ae6b5dac37273d35d4b5cdac2bc4b524dc946130356feb59e853

test:
  secret_key_base: 6857ca8775cba718ca4e1d7461bb1da4685ae17443f8adc4051e9f29d2ef0e59e0df2ac62f98e877a409e5f0a58f2f920a697db2da629dee6d0f85fafbe7f19b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
